spring.application.name=sq-ch12-ex2.1

# Configuração datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/books
spring.datasource.username=davidsonlinhss
spring.datasource.password=Flokiehd@123
spring.datasource.driver-class-name=org.postgresql.Driver
